FROM golang:alpine AS builder

WORKDIR /workspace

COPY go.mod go.sum ./
RUN go mod download

COPY api/ api/
COPY cmd/ cmd/
COPY internal/ internal/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=linux go build -a -o /workspace/saurient-controller cmd/controller/main.go

FROM alpine:3.20
WORKDIR /
COPY --from=builder /workspace/saurient-controller /controller
USER 65532:65532

ENTRYPOINT ["/controller"]
