apiVersion: v1
kind: Namespace
metadata:
  name: saurient-system
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: saurient-system
type: Opaque
stringData:
  POSTGRES_USER: saurient
  POSTGRES_PASSWORD: saurient123
  POSTGRES_DB: saurient_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: saurient-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: saurient-system
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30542
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: saurient-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: saurient-system
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
