package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// CarbonPassportSpec defines the computed carbon passport data for a Product batch.
type CarbonPassportSpec struct {
	TenantID           string  `json:"tenantID"`
	FacilityID         string  `json:"facilityID"`
	BatchID            string  `json:"batchID"`
	CommodityType      string  `json:"commodityType"`
	ProductRef         string  `json:"productRef"`
	DataHash           string  `json:"dataHash"`
	Scope1KgCO2e       float64 `json:"scope1KgCO2e"`
	Scope2KgCO2e       float64 `json:"scope2KgCO2e"`
	Scope3KgCO2e       float64 `json:"scope3KgCO2e"`
	TotalFootprintKg   float64 `json:"totalFootprintKg"`
	CalculationDetails string  `json:"calculationDetails"` // JSON snapshot
}

// CarbonPassportStatus describes the observed state of a CarbonPassport.
type CarbonPassportStatus struct {
	// Phase is one of Calculated, Verified.
	Phase             string      `json:"phase,omitempty"`
	PassportID        string      `json:"passportID,omitempty"`
	CryptographicHash string      `json:"cryptographicHash,omitempty"`
	IssuedAt          metav1.Time `json:"issuedAt,omitempty"`
	LastUpdated       metav1.Time `json:"lastUpdated,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=cp
type CarbonPassport struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CarbonPassportSpec   `json:"spec,omitempty"`
	Status CarbonPassportStatus `json:"status,omitempty"`
}

// DeepCopyInto copies all properties of CarbonPassport into out.
func (in *CarbonPassport) DeepCopyInto(out *CarbonPassport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonPassport.
func (in *CarbonPassport) DeepCopy() *CarbonPassport {
	if in == nil {
		return nil
	}
	out := new(CarbonPassport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CarbonPassport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// +kubebuilder:object:root=true
type CarbonPassportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CarbonPassport `json:"items"`
}

func (in *CarbonPassportList) DeepCopyInto(out *CarbonPassportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CarbonPassport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *CarbonPassportList) DeepCopy() *CarbonPassportList {
	if in == nil {
		return nil
	}
	out := new(CarbonPassportList)
	in.DeepCopyInto(out)
	return out
}

func (in *CarbonPassportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
